import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Minha Festa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="Home">
        <section className="banner">
          <h1 className="title">21 BITS</h1>
          <h2 className="subtitle">O POBRE VAI VOLTAR A COMER PICANHA</h2>
          <button className="Confirm_button">Quero participar</button>
        </section>
      </main>
    </>
  );
}
