import Header from "@/components/header";
import Banner from "@/components/banner";
import Instructions from "@/components/instructions";
import Head from "next/head";
import About from "@/components/about";
export default function Home() {
  return (
    <>
      <Head>
        <title>Minha Festa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Header />
        <Banner />
        <About />
        <Instructions />
      </main>
    </>
  );
}
